apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: registries
spec:
  imageDigestMirrors:
    # certificate-transparency-go
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/certificate-transparency-go/certificate-transparency-go
      source: registry.redhat.io/rhtas/certificate-transparency-rhel9
    # cli
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/cli/cosign
      source: registry.redhat.io/rhtas/cosign-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/cli/gitsign
      source: registry.redhat.io/rhtas/gitsign-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-cg
      source: registry.redhat.io/rhtas/client-server-cg-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/cli/client-server-re
      source: registry.redhat.io/rhtas/client-server-re-rhel9
    # operator
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator-bundle
      source: registry.redhat.io/rhtas/rhtas-operator-bundle   
    - mirrors:
      - quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator
      source: registry.redhat.io/rhtas/rhtas-rhel9-operator      
    # fulcio  
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/fulcio/fulcio-server
      source: registry.redhat.io/rhtas/fulcio-rhel9
    # rekor  
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rekor/rekor-server
      source: registry.redhat.io/rhtas/rekor-server-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rekor/rekor-cli
      source: registry.redhat.io/rhtas/rekor-cli-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rekor/backfill-redis
      source: registry.redhat.io/rhtas/rekor-backfill-redis-rhel9
    # rekor-search-ui
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/rekor-search/rekor-search
      source: registry.redhat.io/rhtas/rekor-search-ui-rhel9
    # trillian
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/trillian/logserver
      source: registry.redhat.io/rhtas/trillian-logserver-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/trillian/logsigner
      source: registry.redhat.io/rhtas/trillian-logsigner-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/trillian/database
      source: registry.redhat.io/rhtas/trillian-database-rhel9   
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/trillian/redis
      source: registry.redhat.io/rhtas/trillian-redis-rhel9
    # scaffold
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/scaffold/ctlog-managectroots
      source: registry.redhat.io/rhtas/ctlog-managectroots-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/scaffold/createctconfig
      source: registry.redhat.io/rhtas/createctconfig-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/scaffold/trillian-createtree
      source: registry.redhat.io/rhtas/trillian-createtree-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/scaffold/trillian-createdb
      source: registry.redhat.io/rhtas/trillian-createdb-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/scaffold/fulcio-createcerts
      source: registry.redhat.io/rhtas/fulcio-createcerts-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/scaffold/tuf-server
      source: registry.redhat.io/rhtas/tuf-server-rhel9
    # segment-backup-job
    - mirrors:
        - quay.io/redhat-user-workloads/rhtas-tenant/segment-backup-job/segment-backup-job
      source: registry.redhat.io/rhtas/segment-reporting-rhel9
