---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtas-operator
  namespace: openshift-operators
spec:
  channel: candidate-v1.0
  installPlanApproval: Automatic
  name: rhtas-operator
  source: ${OPERATOR_SOURCE}
  sourceNamespace: openshift-marketplace