---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtas-operator
  namespace: openshift-operators
spec:
  channel: ${OPERATOR_CHANNEL}
  installPlanApproval: Manual
  name: rhtas-operator
  source: ${OPERATOR_SOURCE}
  sourceNamespace: openshift-marketplace
  startingCSV: rhtas-operator.v${OPERATOR_VERSION}