---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtas-operator
  namespace: openshift-operators
spec:
  channel: stable
  version: 1.0.2
  installPlanApproval: Automatic
  name: rhtas-operator
  source: ${OPERATOR_SOURCE}
  sourceNamespace: openshift-marketplace