name: Multi-OS E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CLUSTER_URL: ${{ secrets.CLUSTER_URL }}
  CLUSTER_TOKEN: ${{ secrets.CLUSTER_TOKEN }}

jobs:
  e2e-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            name: RHEL
    runs-on: ${{ matrix.os }}
    name: E2E Tests on ${{ matrix.name || matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22.0'
  

    - name: Install Git (Ubuntu/RHEL)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Install Git (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install git

    - name: Install Git (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install git
        echo "$env:ChocolateyInstall\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install skopeo (Ubuntu/RHEL)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Install skopeo (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install skopeo

    - name: Install WSL and skopeo (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Enable WSL
        dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
        # Enable Virtual Machine Platform
        dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
        # Install WSL
        wsl --install
        # Update and install skopeo in WSL
        wsl -u root apt-get update
        wsl -u root apt-get install -y skopeo

    - name: OpenShift Client Installer
      uses: redhat-actions/oc-installer@v1
            

    # FORNOW: Display tool versions
    - name: Display tool versions
      run: |
        go version
        git --version
        oc version
        if [ "${{ matrix.os }}" != "windows-latest" ]; then
        skopeo --version
        else
        wsl skopeo --version
        fi

    - name: Log in to cluster
      run: oc login --token=${{ env.CLUSTER_TOKEN }} --server=${{ env.CLUSTER_URL }} --insecure-skip-tls-verify=true

    - name: Clone E2E repository
      run: git clone https://github.com/securesign/sigstore-e2e.git

    - name: Run E2E tests (Ubuntu/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        cd sigstore-e2e
        git checkout skopeo-support
        export CLI_STRATEGY=openshift
        source tas-env-variables.sh
        go test -v ./test/... --ginkgo.v

    - name: Run E2E tests (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd sigstore-e2e
        git checkout skopeo-support
        $env:CLI_STRATEGY = "openshift"
        .\tas-env-variables.ps1
        go test -v ./test/... --ginkgo.v